config/routes.rb
Mads1314SupportReleasing::Application.routes.draw do

  root to: "home#index"
  
  resources :salts, except: ['new'] do
    member do
      get 'verify'
      get 'download'
    end
  end

  resources :documents, except: ['new']

end

app/models/release_document.rb
class ReleaseDocument < ActiveRecord::Base
  attr_accessible :content, :name, :tdoc

  validates_uniqueness_of :name
end

app/models/release_salt.rb
class ReleaseSalt < ActiveRecord::Base
  attr_accessible :content, :name

  validates_uniqueness_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def create
    doc = ReleaseDocument.new
    doc.tdoc = params[:type]
    doc.content = ""
    doc.name = params[:name]
    doc.save
    redirect_to documents_path
  end

  def update
    doc = ReleaseDocument.find(params[:id])
    doc.content = params[:content]
    doc.save
    redirect_to edit_document_path(params[:id])
  end

  def edit
    @doc = ReleaseDocument.find(params[:id])
    render layout: false
  end

  def destroy
    ReleaseDocument.find(params[:id]).delete
    render nothing: true
  end

  def index
    @docs = ReleaseDocument.all()
    render layout: false
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
end

app/controllers/salts_controller.rb
class SaltsController < ApplicationController

  def verify
  end

  def download
  end

  def create
    doc = ReleaseSalt.new
    doc.content = ""
    doc.name = params[:name]
    doc.save
    redirect_to salts_path
  end

  def update
    doc = ReleaseSalt.find(params[:id])
    doc.content = params[:content]
    doc.save
    redirect_to edit_salt_path(params[:id])
  end

  def edit
    @doc = ReleaseSalt.find(params[:id])
    render layout: false
  end

  def destroy
    ReleaseSalt.find(params[:id]).delete
    render nothing: true
  end

  def index
    @docs = ReleaseSalt.all()
    render layout: false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/salt_helper.rb
module SaltHelper
end

app/views/documents/edit.html.erb
<% if @doc %>
	<h2><%= @doc['name'] %></h2>
	<div>
	<%= form_tag document_path(@doc['id']), method: 'put', remote: true, html: '#Documents' do %>
	<% if @doc['tdoc'] == 1 %>
		<%= sketchily_tag 'file_content', @doc['content'], hide_menu: true %>
	<% else %>
		<%= text_area_tag 'file_content', @doc['content'] %>
	<% end %>
		<span class="btns_panel">
		<%= submit_tag 'Save', class: 'btns save' %>
		<% end -%>
		<%= link_to 'Delete', 'javascript:void(0)', onclick: 'deleteDocument(' + @doc['id'].to_s + ');', class: 'btns save' %>
		</span>
	</div>
<% end -%> 
            

app/views/documents/index.html.erb
<% @docs.each_with_index do |value,index| %>
<%= link_to ('<li>' + value['name'] + '</li>').html_safe, 'javascript:void(0)',  onclick: 'editDocument(' + index.to_s + ',"' + edit_document_path(value['id']) + '",' + value['id'].to_s + ');' %>
<% end %>

app/views/home/index.html.erb
 
<h1>Support Release</h1>
<div id = "container">
    <div id ="left">
        <h2>Files</h2>
        <div class="menu">
            <h2 class="files_title">
            	Documents
            </h2>
            <div class="create_doc">
                <%= select_tag "credit_card", options_for_select([ "doc", "svg" ], "doc"), class: "doc_type" -%>
                <input class="new_doc new_doc_with_type" type="text" value="New Document" onfocus="this.value=''" onblur="this.value='New Document'" onkeyup="createDocument(event);" ></input>
            </div>
            <div class="sub_menu">
                <div class="loadImage">
            	</div>
                <ul id="Documents">
                </ul>
            </div>
            <h2 class="files_title">
            	Salt Scripts
            </h2>
            <input class="new_doc new_doc_without_type" type="text" value="New Document" onfocus="this.value=''" onblur="this.value='New Document'" onkeyup="createSaltDocument(event);"></input>
             <div class="sub_menu">
             	<div class="loadImage">
	            </div>
                <ul id="Salt_docs">  
                </ul>
            </div> 
            
        </div>
    </div>
    <div id="content">
        <div id = "middle" style = "position:relative; float:left; width: 40%;margin-right:1%">
            <div class="default_content" >
                    <h2>There is no Document selected</h2>
            </div>
            <div class="content doc_content"></div>
            <div class="loadImage">

            <!--<a class="btns save" href="#save_btn" style="display:none" >Save</a>
            <a class="btns save" href="#delete_btn" style="display:none" >Delete</a>-->
            </div>
        </div>
        <div id = "right" style = "position:relative; float:left; width: 35%;">
            <div class="default_content" >
                    <h2>There is no Salt selected</h2>
            </div>
            <div class="content salt_content" ></div>
            <div class="loadImage"/>
            <!--<a class="btns save" href="#save_btn" style="display:none" >Save</a>
            <a class="btns save" href="#delete_btn" style="display:none" >Delete</a>-->
            </div>
        </div>
    </div>
</div>
 
<script type="text/javascript" >
        loadDocuments();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mads1314SupportReleasing</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/salts/edit.html.erb
<% if @doc %>
	<h2><%= @doc['name'] %></h2>
	<div>
	<%= form_tag salt_path(@doc['id']), method: 'put', remote: true, html: '#Salt_docs' do %>
	<%= text_area_tag 'content', @doc['content']  %>
	<span class="btns_panel salt_btns_panel">
	<%= submit_tag 'Save', class: 'btns save' %>
	<% end -%>
	<%= link_to 'Delete', 'javascript:void(0)', onclick: 'deleteSalt(' + @doc['id'].to_s + ');', class: 'btns save' %>
	<span>
	</div>
<% end -%> 

app/views/salts/index.html.erb
<% @docs.each_with_index do |value,index| %>
<%= link_to ('<li>' + value['name'] + '</li>').html_safe, 'javascript:void(0)',  onclick: 'editSalt(' + index.to_s + ',"' + edit_salt_path(value['id']) + '",' + value['id'].to_s + ');' %>
<%# link_to ('<li>' + t['name'] + '</li>').html_safe, edit_salt_path(t['id']), :html => { :id => "middle"} %>
<% end %>